name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Close PRs that contain content for services that have been migrated out of the azure-docs-pr repository.
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - or:
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/aks/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/defender-for-cloud/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/attestation/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/confidential-ledger/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/dedicated-hsm/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/key-vault/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/payment-hsm/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/postgresql/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/cosmos-db/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/dms/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/mariadb/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/mysql/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/managed-instance-apache-cassandra/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/virtual-machines/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/virtual-machines-scale-sets/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/container-instances/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/service-fabric/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/machine-learning/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/ai-studio/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/ai-services/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/genomics/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/open-datasets/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/search/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/azure-monitor/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/advisor/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/chaos-studio/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/service-health/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/azure-arc/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/azure-linux/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/azure-portal/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/copilot/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/lighthouse/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/quotas/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/container-registry/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/kubernetes-fleet/*
        then:
          - addReply:
              reply: >-
                @${issueAuthor} - You tried to add content to a folder path that has been removed from this repository. Your pull request will be automatically closed. Submit your changes to the updated repository, which can be identified by clicking the Edit this Document link at the top of any published article for that product or service.
          - closePullRequest

      - description: Alert authors to edits in the /articles/reliability folder.
        if:
          # If a PR in the articles/reliability folder is opened, and the PR author isn't Anastasia or John...
          - payloadType: Pull_Request
          - filesMatchPattern:
              matchAny: true
              pattern: articles/reliability/*
          - isAction:
              action: Opened
          - not:
              or:
                - isActivitySender:
                    user: anaharris-ms
                - isActivitySender:
                    user: johndowns
        then:
          # Mention Anastasia and John, add a reply asking the PR author not to sign off on the PR, and add the needs-human-review label.
          - mentionUsers:
              mentionees:
                - anaharris-ms
                - johndowns
              replyTemplate: >-
                Tagging authors for this folder: ${mentionees}
          - addReply:
              reply: >-
                @${issueAuthor} - Please do NOT sign off on this pull request. The Reliability Hub owners will sign off for you.
          - addLabel:
              label: needs-human-review

      - description: Disallow sign-off for articles in the /articles/reliability folder.
        if:
          # If a 'sign-off' comment is added to a PR in the articles/reliability folder , and the PR author isn't Anastasia or John...
          - payloadType: Issue_Comment
          - isPullRequest
          - filesMatchPattern:
              matchAny: true
              pattern: articles/reliability/*
          - commentContains:
              pattern: \#sign-off
              isRegex: false
          - not:
              or:
                - isActivitySender:
                    user: anaharris-ms
                - isActivitySender:
                    user: johndowns
        then:
          # Add the do-not-merge label, remove the ready-to-merge label, and add a reply asking the PR author not to sign off on the PR.
          - addReply:
              reply: >-
                @${issueAuthor} - Please do NOT sign off on this pull request. The Reliability Hub owners will sign off for you.
          - addLabel:
              label: do-not-merge
          - removeLabel:
              label: ready-to-merge
      
      - description: Write a message if the breadcrumb file is modified in the azure-docs-pr repository.
        if:
        - payloadType: Pull_Request
        - isAction:
            action: Opened
        - filesMatchPattern:
              matchAny: true
              pattern: bread/*
              
        then:
          - addReply:
              reply: >-
                @${issueAuthor} - This PR modifies the breadcrumb file for the entire repository: bread/toc.yml. This file supports the on-site navigation for 100s of services. Please make sure your changes to the breadcrumb file are intentional. Do not delete this file. 
          
