articles/data-factory/data-factory-api-change-log.md
articles/data-factory/data-factory-azure-blob-connector.md
articles/data-factory/data-factory-azure-datalake-connector.md
articles/data-factory/data-factory-azure-documentdb-connector.md
articles/data-factory/data-factory-azure-ml-batch-execution-activity.md
articles/data-factory/data-factory-azure-sql-connector.md
articles/data-factory/data-factory-azure-sql-data-warehouse-connector.md
articles/data-factory/data-factory-azure-table-connector.md
articles/data-factory/data-factory-build-your-first-pipeline-using-editor.md
articles/data-factory/data-factory-build-your-first-pipeline-using-powershell.md
articles/data-factory/data-factory-build-your-first-pipeline-using-vs.md
articles/data-factory/data-factory-build-your-first-pipeline.md
articles/data-factory/data-factory-common-scenarios.md
articles/data-factory/data-factory-compute-linked-services.md
articles/data-factory/data-factory-create-data-factories-programmatically.md
articles/data-factory/data-factory-create-datasets.md
articles/data-factory/data-factory-create-pipelines.md
articles/data-factory/data-factory-create-predictive-pipelines.md
articles/data-factory/data-factory-customer-case-studies.md
articles/data-factory/data-factory-customer-profiling-usecase.md
articles/data-factory/data-factory-data-movement-activities.md
articles/data-factory/data-factory-data-transformation-activities.md
articles/data-factory/data-factory-editor.md
articles/data-factory/data-factory-faq.md
articles/data-factory/data-factory-get-started-using-editor.md
articles/data-factory/data-factory-get-started-using-vs.md
articles/data-factory/data-factory-get-started.md
articles/data-factory/data-factory-hadoop-streaming-activity.md
articles/data-factory/data-factory-hive-activity.md
articles/data-factory/data-factory-introduction.md
articles/data-factory/data-factory-map-reduce.md
articles/data-factory/data-factory-monitor-manage-pipelines.md
articles/data-factory/data-factory-monitor-manage-using-powershell.md
articles/data-factory/data-factory-move-data-between-onprem-and-cloud.md
articles/data-factory/data-factory-naming-rules.md
articles/data-factory/data-factory-onprem-db2-connector.md
articles/data-factory/data-factory-onprem-file-system-connector.md
articles/data-factory/data-factory-onprem-mysql-connector.md
articles/data-factory/data-factory-onprem-oracle-connector.md
articles/data-factory/data-factory-onprem-postgresql-connector.md
articles/data-factory/data-factory-onprem-sybase-connector.md
articles/data-factory/data-factory-onprem-teradata-connector.md
articles/data-factory/data-factory-pig-activity.md
articles/data-factory/data-factory-product-reco-usecase.md
articles/data-factory/data-factory-release-notes.md
articles/data-factory/data-factory-samples.md
articles/data-factory/data-factory-scheduling-and-execution.md
articles/data-factory/data-factory-sdks.md
articles/data-factory/data-factory-sqlserver-connector.md
articles/data-factory/data-factory-stored-proc-activity.md
articles/data-factory/data-factory-terminology.md
articles/data-factory/data-factory-troubleshoot.md
articles/data-factory/data-factory-tutorial-extend-onpremises-using-powershell.md
articles/data-factory/data-factory-tutorial-extend-onpremises.md
articles/data-factory/data-factory-tutorial-using-powershell.md
articles/data-factory/data-factory-tutorial.md
articles/data-factory/data-factory-use-custom-activities.md
articles/data-factory/data-factory-usql-activity.md
articles/documentdb/documentdb-consistency-levels.md
articles/documentdb/documentdb-create-account.md
articles/documentdb/documentdb-create-collection.md
articles/documentdb/documentdb-create-database.md
articles/documentdb/documentdb-create-documentdb-website.md
articles/documentdb/documentdb-dotnet-application.md
articles/documentdb/documentdb-faq.md
articles/documentdb/documentdb-geospatial.md
articles/documentdb/documentdb-get-started.md
articles/documentdb/documentdb-import-data.md
articles/documentdb/documentdb-increase-limits.md
articles/documentdb/documentdb-indexing-policies.md
articles/documentdb/documentdb-indexing.md
articles/documentdb/documentdb-introduction.md
articles/documentdb/documentdb-java-application.md
articles/documentdb/documentdb-limits.md
articles/documentdb/documentdb-manage-account.md
articles/documentdb/documentdb-manage.md
articles/documentdb/documentdb-modeling-data.md
articles/documentdb/documentdb-monitor-accounts.md
articles/documentdb/documentdb-nodejs-application.md
articles/documentdb/documentdb-nodejs-get-started.md
articles/documentdb/documentdb-orderby.md
articles/documentdb/documentdb-partition-data.md
articles/documentdb/documentdb-performance-levels.md
articles/documentdb/documentdb-powerbi-visualize.md
articles/documentdb/documentdb-programming.md
articles/documentdb/documentdb-python-application.md
articles/documentdb/documentdb-query-collections-query-explorer.md
articles/documentdb/documentdb-resources.md
articles/documentdb/documentdb-run-hadoop-with-hdinsight.md
articles/documentdb/documentdb-search-indexer.md
articles/documentdb/documentdb-secure-access-to-data.md
articles/documentdb/documentdb-sharding.md
articles/documentdb/documentdb-sql-query-cheat-sheet.md
articles/documentdb/documentdb-sql-query.md
articles/documentdb/documentdb-use-cases.md
articles/documentdb/documentdb-view-json-document-explorer.md
articles/documentdb/documentdb-view-scripts.md
articles/documentdb/documentdb-whitepaper-chappell.md
articles/documentdb/fundamentals-data-management-nosql-chappell.md
articles/sql-data-warehouse/sql-data-warehouse-get-started-provision.md
articles/sql-data-warehouse/sql-data-warehouse-load-with-polybase-short.md
articles/sql-data-warehouse/sql-data-warehouse-load-with-polybase.md
articles/sql-data-warehouse/sql-data-warehouse-overview-reference.md
articles/sql-data-warehouse/sql-data-warehouse-overview-what-is.md
articles/sql-data-warehouse/sql-data-warehouse-overview-workload.md
articles/sql-data-warehouse/sql-data-warehouse-reference-powershell-cmdlets.md
articles/sql-data-warehouse/sql-data-warehouse-reference-tsql-language-elements.md
articles/sql-data-warehouse/sql-data-warehouse-reference-tsql-statements.md
articles/sql-data-warehouse/sql-data-warehouse-reference-tsql-system-views.md
articles/sql-database/fundamentals-data-management-business-analytics.md
articles/sql-database/sql-database-elastic-jobs-create-and-manage.md
articles/sql-database/sql-database-elastic-jobs-service-installation.md
articles/sql-database/sql-database-elastic-scale-split-merge-security-configuration.md
articles/sql-database/sql-database-get-started-sql-data-sync.md
