REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-accessmanagement-group-saasapps.md --destination articles/active-directory/users-groups-roles/groups-saasapps.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-accessmanagement-groups-settings-cmdlets.md --destination articles/active-directory/users-groups-roles/groups-settings-cmdlets.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-accessmanagement-groups-settings-v2-cmdlets.md --destination articles/active-directory/users-groups-roles/groups-settings-v2-cmdlets.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-accessmanagement-self-service-group-management.md --destination articles/active-directory/users-groups-roles/groups-self-service-management.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-accessmanagement-troubleshooting.md --destination articles/active-directory/users-groups-roles/groups-troubleshooting.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-admin-manage-emergency-access-accounts.md --destination articles/active-directory/users-groups-roles/directory-emergency-access.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-administrative-units-management.md --destination articles/active-directory/users-groups-roles/directory-administrative-units.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-assign-admin-roles-azure-portal.md --destination articles/active-directory/users-groups-roles/directory-assign-admin-roles.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-domains-manage-azure-portal.md --destination articles/active-directory/users-groups-roles/domains-manage.md

REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-groups-dynamic-membership-azure-portal.md --destination articles/active-directory/users-groups-roles/groups-dynamic-membership.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-groups-lifecycle-azure-portal.md --destination articles/active-directory/users-groups-roles/groups-lifecycle.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-licensing-directory-independence.md --destination articles/active-directory/users-groups-roles/licensing-directory-independence.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-licensing-group-advanced.md --destination articles/active-directory/users-groups-roles/licensing-group-advanced.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-licensing-group-assignment-azure-portal.md --destination articles/active-directory/users-groups-roles/licensing-groups-assign.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-licensing-group-migration-azure-portal.md --destination articles/active-directory/users-groups-roles/licensing-groups-migrate-users.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-licensing-group-problem-resolution-azure-portal.md --destination articles/active-directory/users-groups-roles/licensing-groups-resolve-problems.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-licensing-group-product-migration.md --destination articles/active-directory/users-groups-roles/licensing-groups-change-licenses.md
REM movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-licensing-product-and-service-plan-reference.md --destination articles/active-directory/users-groups-roles/licensing-service-plan-reference.md

movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-licensing-ps-examples.md --destination articles/active-directory/users-groups-roles/licensing-ps-examples.md
movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-self-service-signup.md --destination articles/active-directory/users-groups-roles/directory-self-service-signup.md
movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/active-directory-service-limits-restrictions.md --destination articles/active-directory/users-groups-roles/directory-service-limits-restrictions.md
movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/admin-roles-best-practices.md --destination articles/active-directory/users-groups-roles/directory-admin-roles-secure.md
movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/directory-delete-howto.md --destination articles/active-directory/users-groups-roles/directory-delete-howto.md
movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/domains-admin-takeover.md --destination articles/active-directory/users-groups-roles/domains-admin-takeover.md
movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/groups-naming-policy.md --destination articles/active-directory/users-groups-roles/groups-naming-policy.md
movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/linkedin-integration.md --destination articles/active-directory/users-groups-roles/linkedin-integration.md
