:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/custom-consent-permissions.md --destination articles/active-directory/roles/custom-consent-permissions.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-view-assignments.md --destination articles/active-directory/roles/custom-view-assignments.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/directory-admin-roles-secure.md --destination articles/active-directory/roles/security-planning.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/directory-emergency-access.md --destination articles/active-directory/roles/security-emergency-access.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-quickstart-app-registration-limits.md --destination articles/active-directory/roles/quickstart-app-registration-limits.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/directory-assign-admin-roles.md --destination articles/active-directory/roles/permissions-reference.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/my-staff-configure.md --destination articles/active-directory/roles/my-staff-configure.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/directory-manage-roles-portal.md --destination articles/active-directory/roles/manage-roles-portal.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-m365-workload-docs.md --destination articles/active-directory/roles/m365-workload-docs.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-groups-view-assignments.md --destination articles/active-directory/roles/groups-view-assignments.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-groups-remove-assignment.md --destination articles/active-directory/roles/groups-remove-assignment.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-groups-pim-eligible.md --destination articles/active-directory/roles/groups-pim-eligible.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-groups-faq-troubleshooting.md --destination articles/active-directory/roles/groups-faq-troubleshooting.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-groups-create-eligible.md --destination articles/active-directory/roles/groups-create-eligible.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-groups-concept.md --destination articles/active-directory/roles/groups-concept.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-groups-assign-role.md --destination articles/active-directory/roles/groups-assign-role.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-delegate-by-task.md --destination articles/active-directory/roles/delegate-by-task.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-delegate-app-roles.md --destination articles/active-directory/roles/delegate-app-roles.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-custom-overview.md --destination articles/active-directory/roles/custom-overview.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/custom-enterprise-apps.md --destination articles/active-directory/roles/custom-enterprise-apps.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/custom-enterprise-app-permissions.md --destination articles/active-directory/roles/custom-enterprise-app-permissions.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-create-custom.md --destination articles/active-directory/roles/custom-create.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-custom-available-permissions.md --destination articles/active-directory/roles/custom-available-permissions.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-assign-powershell.md --destination articles/active-directory/roles/custom-assign-powershell.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-assign-graph.md --destination articles/active-directory/roles/custom-assign-graph.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-concept-delegation.md --destination articles/active-directory/roles/concept-delegation.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-admin-units-manage.md --destination articles/active-directory/roles/admin-units-manage.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-admin-units-faq-troubleshoot.md --destination articles/active-directory/roles/admin-units-faq-troubleshoot.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-admin-units-assign-roles.md --destination articles/active-directory/roles/admin-units-assign-roles.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-admin-units-add-manage-users.md --destination articles/active-directory/roles/admin-units-add-manage-users.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/roles-admin-units-add-manage-groups.md --destination articles/active-directory/roles/admin-units-add-manage-groups.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/directory-administrative-units.md --destination articles/active-directory/roles/administrative-units.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/users-sharing-accounts.md --destination articles/active-directory/enterprise-users/users-sharing-accounts.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/users-search-enhanced.md --destination articles/active-directory/enterprise-users/users-search-enhanced.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/users-revoke-access.md --destination articles/active-directory/enterprise-users/users-revoke-access.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/users-restrict-guest-permissions.md --destination articles/active-directory/enterprise-users/users-restrict-guest-permissions.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/users-close-account.md --destination articles/active-directory/enterprise-users/users-close-account.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/users-bulk-restore.md --destination articles/active-directory/enterprise-users/users-bulk-restore.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/users-bulk-download.md --destination articles/active-directory/enterprise-users/users-bulk-download.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/users-bulk-delete.md --destination articles/active-directory/enterprise-users/users-bulk-delete.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/users-bulk-add.md --destination articles/active-directory/enterprise-users/users-bulk-add.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/signin-realm-discovery.md --destination articles/active-directory/enterprise-users/signin-realm-discovery.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/signin-account-support.md --destination articles/active-directory/enterprise-users/signin-account-support.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/linkedin-user-consent.md --destination articles/active-directory/enterprise-users/linkedin-user-consent.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/linkedin-integration.md --destination articles/active-directory/enterprise-users/linkedin-integration.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/licensing-service-plan-reference.md --destination articles/active-directory/enterprise-users/licensing-service-plan-reference.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/licensing-ps-examples.md --destination articles/active-directory/enterprise-users/licensing-ps-examples.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/licensing-groups-resolve-problems.md --destination articles/active-directory/enterprise-users/licensing-groups-resolve-problems.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/licensing-groups-migrate-users.md --destination articles/active-directory/enterprise-users/licensing-groups-migrate-users.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/licensing-groups-change-licenses.md --destination articles/active-directory/enterprise-users/licensing-groups-change-licenses.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/licensing-groups-assign.md --destination articles/active-directory/enterprise-users/licensing-groups-assign.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/licensing-group-advanced.md --destination articles/active-directory/enterprise-users/licensing-group-advanced.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/licensing-directory-independence.md --destination articles/active-directory/enterprise-users/licensing-directory-independence.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-troubleshooting.md --destination articles/active-directory/enterprise-users/groups-troubleshooting.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-settings-v2-cmdlets.md --destination articles/active-directory/enterprise-users/groups-settings-v2-cmdlets.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-settings-cmdlets.md --destination articles/active-directory/enterprise-users/groups-settings-cmdlets.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-self-service-management.md --destination articles/active-directory/enterprise-users/groups-self-service-management.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-saasapps.md --destination articles/active-directory/enterprise-users/groups-saasapps.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-restore-deleted.md --destination articles/active-directory/enterprise-users/groups-restore-deleted.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-quickstart-naming-policy.md --destination articles/active-directory/enterprise-users/groups-quickstart-naming-policy.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-quickstart-expiration.md --destination articles/active-directory/enterprise-users/groups-quickstart-expiration.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-naming-policy.md --destination articles/active-directory/enterprise-users/groups-naming-policy.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-members-owners-search.md --destination articles/active-directory/enterprise-users/groups-members-owners-search.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-lifecycle.md --destination articles/active-directory/enterprise-users/groups-lifecycle.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-dynamic-tutorial.md --destination articles/active-directory/enterprise-users/groups-dynamic-tutorial.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-dynamic-rule-validation.md --destination articles/active-directory/enterprise-users/groups-dynamic-rule-validation.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-dynamic-membership.md --destination articles/active-directory/enterprise-users/groups-dynamic-membership.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-create-rule.md --destination articles/active-directory/enterprise-users/groups-create-rule.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-change-type.md --destination articles/active-directory/enterprise-users/groups-change-type.md
:: C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-bulk-remove-members.md --destination articles/active-directory/enterprise-users/groups-bulk-remove-members.md
C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-bulk-import-members.md --destination articles/active-directory/enterprise-users/groups-bulk-import-members.md
C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-bulk-download-members.md --destination articles/active-directory/enterprise-users/groups-bulk-download-members.md
C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-bulk-download.md --destination articles/active-directory/enterprise-users/groups-bulk-download.md
C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/groups-assign-sensitivity-labels.md --destination articles/active-directory/enterprise-users/groups-assign-sensitivity-labels.md
C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/domains-manage.md --destination articles/active-directory/enterprise-users/domains-manage.md
C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/domains-admin-takeover.md --destination articles/active-directory/enterprise-users/domains-admin-takeover.md
C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/directory-service-limits-restrictions.md --destination articles/active-directory/enterprise-users/directory-service-limits-restrictions.md
C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/directory-self-service-signup.md --destination articles/active-directory/enterprise-users/directory-self-service-signup.md
C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/directory-overview-user-model.md --destination articles/active-directory/enterprise-users/directory-overview-user-model.md
C:\Users\curtand\source\repos\Azure-CSI-Content-Tools\Tools\DrMove\movemd\bin\Debug\movemd.exe --redirect-file --repo-directory C:\Users\curtand\azure-docs-pr --source articles/active-directory/users-groups-roles/directory-delete-howto.md --destination articles/active-directory/enterprise-users/directory-delete-howto.md
