---
config:
  look: neo
  theme: default
---
sequenceDiagram
  actor User as User
  participant Entra ID as Entra ID
  participant Azure Monitor as Azure Monitor
  participant Log Analytics Workspace as Log Analytics Workspace
  participant VM as VM
  User ->> Entra ID: 1. Register Microsoft Entra application
  Entra ID ->> User: Provide Application ID and secret
  User ->> Entra ID: 2. Assign the Monitoring Metrics Publisher role to the application
  User ->> Azure Monitor: 3. Create a DCE, DCR, and custom Auxiliary table by deploying ARM template
  Azure Monitor ->> User: Provide DCE URI and DCR Immutable ID
  User ->> Azure Monitor: 4. Grant your application permission to send data to the DCE
  User ->> VM: 4. Update Logstash configuration file
  VM ->> Azure Monitor: Send data to DCE
  Azure Monitor ->> Log Analytics Workspace: Ingest raw data into CommonSecurityLog_CL table
  User ->> Azure Monitor: 5. Create summary rule
  VM ->> Azure Monitor: Send data to DCE
  Azure Monitor ->> Log Analytics Workspace: Ingest raw data into CommonSecurityLog_CL table
  Azure Monitor ->> Log Analytics Workspace: Ingest aggregated data into a new custom table
