stateDiagram-v2
    TempSensor
    note right of TempSensor: 🆕 Is the identity of EdgeGateway correct?

    TempSensor --> EdgeGateway
    note left of EdgeGateway: 🆕 Is the TempSensor device legitimate?
    note right of EdgeGateway: ✅ Is the identity of ContosoIotHub correct?

    EdgeGateway --> ContosoIotHub
    note left of ContosoIotHub: ✅ Is this device EdgeGateway?