apiVersion: v1
kind: Namespace
metadata:
  name: test-infra
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: https-app
  name: https-app
  namespace: test-infra
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: https-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-app
  namespace: test-infra
spec:
  selector:
    matchLabels:
      app: https-app
  replicas: 2
  template:
    metadata:
      labels:
        app: https-app
    spec:
      containers:
        - name: https-app
          imagePullPolicy: Always
          image: nginx:1.23.2
          ports:
            - containerPort: 8443
          volumeMounts:
          - mountPath: /etc/nginx/ssl
            name: secret-volume
          - mountPath: /etc/nginx/conf.d
            name: configmap-volume
          resources:
            limits:
              cpu: 700m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 20Mi
      volumes:
      - name: secret-volume
        secret:
          secretName: contoso.xyz
      - name: configmap-volume
        configMap:
          name: https-app-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: https-app-cm
  namespace: test-infra
data:
  default.conf: |-
    server {
        listen 8443 ssl;
        server_name contoso.xyz;
        root /usr/share/nginx/html;
        index index.html;
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
        location / {
          return 200 "Hello World!";
        }
    }
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEbXpDQ0FvT2dBd0lCQWdJVUYrWG9tZldlS1haRkI2V1NGbG9HVzhrWERic3dEUVlKS29aSWh2Y05BUUVMDQpCUUF3WERFTE1Ba0dBMVVFQmhNQ1ZWTXhGVEFUQmdOVkJBZ01ERTV2Y25Sb0lFUmhhMjkwWVRFT01Bd0dBMVVFDQpCd3dGUm1GeVoyOHhFREFPQmdOVkJBb01CME52Ym5SdmMyOHhGREFTQmdOVkJBTU1DMk52Ym5SdmMyOHVlSGw2DQpNQ0FYRFRJME1URXdOekU1TVRBek0xb1lEekl4TWpNeE1ERTFNVGt4TURNeldqQmNNUXN3Q1FZRFZRUUdFd0pWDQpVekVWTUJNR0ExVUVDQXdNVG05eWRHZ2dSR0ZyYjNSaE1RNHdEQVlEVlFRSERBVkdZWEpuYnpFUU1BNEdBMVVFDQpDZ3dIUTI5dWRHOXpiekVVTUJJR0ExVUVBd3dMWTI5dWRHOXpieTU0ZVhvd2dnRWlNQTBHQ1NxR1NJYjNEUUVCDQpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ1hNcXZURkV2b3RBaHU1U0lyS3hXemZSRmRJcFBFaTFpNldWV3prNGlZDQpMTGowQUJRRi82bjRMdDRsMDE0bU01QUFxY1lJcG81SDVHOXZNYWpZcFMyYXIvVitIaWtFeU5EMHZhb1A2QVI5DQpWRThLelg5cFM5MldkMDFtWjNXdm12ckdWVUZCWmRWN28zc3g2NXpBR3NKZmZiV1pTNzNLeWZIbHZYcytrY253DQpRWkttV2xrcE5XL1lIcStzMForNk9UYXpIQXIzV3VUUG1BbzRaeCtsTTZ3MGR3N0VQUG1DVDdneUJLeVZxN0JDDQpCdktXeVRVMk9FQUtibW91UXVDelA2RmVRM0UxUWZmWTEzVW9rdmNGMUxMVGlCUDE4ZkR2TDZMcWdaOC9temo5DQpyamo0cnVYK0crS0hBYWdpKytBY2pUMGpNU1A5MmNVT0NqMFY5VTJ5WC9xN0FnTUJBQUdqVXpCUk1CMEdBMVVkDQpEZ1FXQkJRQzhZTkNZTDdzbWE1WWNCZmJtK0REbFpSVnpUQWZCZ05WSFNNRUdEQVdnQlFDOFlOQ1lMN3NtYTVZDQpjQmZibStERGxaUlZ6VEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUE4DQpqVGl2TFdDUElGTExTL29VR0tsMzVBdlNKT0FocjhGNmhrNExESXA3MDl1THc1cWs3SjdNdW0zY1V3Ly9ldUNuDQpZRm92UStGeTVIcGQwL0l3RUxxcG04Tm03dHJtVlVjeWFYZER2cDBvS2kycFdWZTZ3NVhDSXI3a0J6L1kxUUVDDQpsd2pTaFRhVFc4bDl6VUZPai9hdllGeEJ4TDNyNTlRRXcvczBhOG9HUUI1K3JTZ2pqVXNKMVF5Z0ZtVTF2UjAwDQpyMDhvUjkxQzl6YU9DODEvRlVGRmszYSs3MVR2ZjRHSzZHVVRyT1k4eTJwL2V0aGdUSEZlZi9MOFJTR3BCbnFFDQorZzNsZ3VGakZMazNGSFJIV0U2RFpuV01IMjZ4endtSnNwdnFkQWlzTk1vZlRjVGM5Wi85SlRaaGtxL2prUXAvDQpNdDNJTDJPcWdRUHBlOEZQdXlwVA0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUUNYTXF2VEZFdm90QWh1DQo1U0lyS3hXemZSRmRJcFBFaTFpNldWV3prNGlZTExqMEFCUUYvNm40THQ0bDAxNG1NNUFBcWNZSXBvNUg1Rzl2DQpNYWpZcFMyYXIvVitIaWtFeU5EMHZhb1A2QVI5VkU4S3pYOXBTOTJXZDAxbVozV3ZtdnJHVlVGQlpkVjdvM3N4DQo2NXpBR3NKZmZiV1pTNzNLeWZIbHZYcytrY253UVpLbVdsa3BOVy9ZSHErczBaKzZPVGF6SEFyM1d1VFBtQW80DQpaeCtsTTZ3MGR3N0VQUG1DVDdneUJLeVZxN0JDQnZLV3lUVTJPRUFLYm1vdVF1Q3pQNkZlUTNFMVFmZlkxM1VvDQprdmNGMUxMVGlCUDE4ZkR2TDZMcWdaOC9temo5cmpqNHJ1WCtHK0tIQWFnaSsrQWNqVDBqTVNQOTJjVU9DajBWDQo5VTJ5WC9xN0FnTUJBQUVDZ2dFQUFxTkRBQ0cxMlU5d0U0OHljMmV0cnozdi92SDFlMU9scnAvcHNOZW9FR1RuDQpWOHBsNUZ6bUl1QkpHOXZUZVZNam9Lb0FQSEptRlF4VkxWbHViLzUzRElzaiswUHlHZXFabi9ZWEcyNlpkWE9kDQpGV1ovRElxTm5teGlaZlpKYi91Q0xkSkZteXNpK0U4MzBsSjJuNXRYNTJ2b0E4Nmdkd000UEhaN3lmR24xanNuDQp3d1ZsRkMvQWtFaER1TWlCVG9MUW9xaFpHZHl0YmRzZ24rcEFaM1FqbW0ySG1abXFabDJGU1htNVgwdk0vZUYvDQp2VDYzajNoOGNnOGRkQ21YZC84Rm5Wa3ZmNzNFc0VEQzkyZ3ZZQTlNUVZKT2tucjBnbHduSFlKYTUwTzdqYjJhDQp6SXZlbEREaFVON2VwdDZ5K0ZtQTVnMi8zYlVJcE9QKy93UE14NmJaTVFLQmdRREc4MWpBdm1PMHl6a21laHlTDQpaQ1pBemlJd1dvVDc0Zi8rY05JM1QrS3Rwbkpnemd4UGN2MW5pMitCK2lVK0JybnBDNWtkM1o1M1JNZ2g4cERJDQpxTzZtZDZ5dStWWC9Gd3FIMWtUS1hMSlJ2bWVTUGhLSTh4ci9WSjQwMzNyL2hTNnJEZU5CKzRualRuYWYzbllEDQpIYnRFVnJLYjdpTlRvazQvcXJ6MFBYQlRqd0tCZ1FEQ2plQ1Zob3dBbWw2WUNqUTJBazVEVmNFSkkyRGtDREJZDQpIMDVoVHhNYjFaQmtIalc5VHhQL1g1b05SVzUvbG91RWhwdUpESFpHeUx1OHJWc0FqRGk4YkNnYnZRNWJhNlVZDQozdldoZkRQR0FCcHBENy84cWE4YVZPeTZLK05KdGIwVkgzemZRZFZIaGg5ZGowM0Y3QTRscmVYWVYzVzY0UkUvDQp4SFNOT2pUZ0ZRS0JnUUNuTWJLUXFHL2FiRDhuR3RBUUpxSVBMQ3lIUGtzcjh3M1RvclRIVHhkTW4ralhlZEhXDQpvdWhhc0UrUmg4cnNpWEtMYXZmT3BZU2E3dTdSdUt2OE5odjVRZkdaU21qKzZ6b3FWZU9SdkwwTy9WakZDZTFCDQpzaXdxRDg2MDJHcmhlZWR5VVVWL0dna1RRY2xuS09rOFRTd25qa1NqemtsWjY3aWV3TG55OS84QitRS0JnQkxQDQpKS2RRR3JqME03RC9TNHp0TENQV1pwTTdtR0p6YURrY3piY2FyZjVDNTNMR2VPdVVlWnAyNDYza3lJb05RKy9NDQpFNzFzTndNZzVRV1l2UE9RbXV1Y2lVUWxRdjRUcWlKOWE4SHhBQkJrY2lrMkhKbVF6aHo5bU9WbTJOS0hmNEJMDQpTd2RLbGhRVUkzUW9KcHk3OWFJdTdjbThxdVVtWFVTTStiZXRxTzhCQW9HQUg5bEh3SkxmVTVjOUxna0xibE9DDQpjVTQycGMxUEJIY3BNbTNBTVNta1FpdHVQTXdQVEJnUkRtSmxRTFdXMUswZ1lWdGVNNXVRRlBRMzJMeW95Ry9aDQp1aEZsQmd5WGpPOUtYNTNYZ0ZSRmh1aG83WDlzKy9HK1VYRGpUWDU0VUsxcUt6eUhZcmVlVngzUmxhekdSdmdLDQo2UlNPTXI2c2JtTlMxd3pMU2FSN01tYz0NCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0NCg==
kind: Secret
metadata:
  name: contoso.xyz
  namespace: test-infra
type: kubernetes.io/tls
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEbXpDQ0FvT2dBd0lCQWdJVURON0FhSGpMdEFVQndCME1TcjJ1aHJ0U3p2RXdEUVlKS29aSWh2Y05BUUVMDQpCUUF3WERFTE1Ba0dBMVVFQmhNQ1ZWTXhGVEFUQmdOVkJBZ01ERTV2Y25Sb0lFUmhhMjkwWVRFT01Bd0dBMVVFDQpCd3dGUm1GeVoyOHhFREFPQmdOVkJBb01CME52Ym5SdmMyOHhGREFTQmdOVkJBTU1DMk52Ym5SdmMyOHVZMjl0DQpNQ0FYRFRJME1URXdOekU1TVRBek0xb1lEekl4TWpNeE1ERTFNVGt4TURNeldqQmNNUXN3Q1FZRFZRUUdFd0pWDQpVekVWTUJNR0ExVUVDQXdNVG05eWRHZ2dSR0ZyYjNSaE1RNHdEQVlEVlFRSERBVkdZWEpuYnpFUU1BNEdBMVVFDQpDZ3dIUTI5dWRHOXpiekVVTUJJR0ExVUVBd3dMWTI5dWRHOXpieTVqYjIwd2dnRWlNQTBHQ1NxR1NJYjNEUUVCDQpBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzh3QnpSQ0gzQkoxMzZKSldMQzZORXpFam9Zd1VZUS83eVEvODFqNTBzDQpJWmRrcE4zZUlFb1hHRk53R1IvR25QM2NNTHJyY3psYXhCbUVVOXErRmY4M0d2dnUyMEsxOEs4YU1MWmJ0dWFUDQpEUC9CYnA4dWMzNUVNVEp2MWo3UWlqUEpYb3FTeXlwMzl1M3ZDdUZLMGRoZiswaW5za2NQdSs0THZUVWQxdEpYDQp2NDRwd01ESzBjWWZqY1dIY3ZZSXdCL3RXUDRZRVlIQzJkMkN6cTgwQzZNUjQrTlVGZUVnaXk3eFFON0IzSlF4DQpyaVQ1ZmRIeEVkOXgvcW0rRlljdVZleEp0ZHBtSG1TcGt6ZTFsQzdBSDZRaS9xbERtRVBaaHBSMVVwRThkQXlqDQpHdmV1eFhIbmNzMjh0NndoeUxlTzdFdDBvTnMxa3dXUzRHS05PYVRUOHNmcEFnTUJBQUdqVXpCUk1CMEdBMVVkDQpEZ1FXQkJUd1RFaUpZR1hhOGdvWTUzakFtdUI0M2RHcTVqQWZCZ05WSFNNRUdEQVdnQlR3VEVpSllHWGE4Z29ZDQo1M2pBbXVCNDNkR3E1akFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFtDQpiSktXaDRSdmZvS25lY3JVSjZ2dXppaTZNTmg3Mm1zbVc1RjFzTjMzc0dqeU40QmgwajhEYzZjVXpHYlJsdk90DQphenZuV1hSazlCUW9BM01ULzdaZ1NJMDV6VUlnQ2N0UjJzYnE1ajRRemNQQS9HbVpzdnZ5N0ZIcExmVVdrdE1wDQpiRlhWVExRaFA3QWQzVko2VDVTaytsZ0IvcUFtL0FWWlYwTXpabWRVRXlqa0pndGJjQXpKNG1JdC8reFZ6V3JJDQo2NTRYcy9GN2xlbTdXZWxQZzhQVUxvNXZYQy9RSjdhakhSZW9CdGkwclV3blVDREVUOHoyQk0va3lzODhKWUhCDQpZRzNCdmJCRW9MSnZKT3JncXpleitCVURiTFAxTkJKTWpuSTJBbW02S244Y2UrMjFYTFZBSmJGSm9HclpGN1VNDQpac1VKRVdob3FXRllXa3BHOXA3aw0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUM4d0J6UkNIM0JKMTM2DQpKSldMQzZORXpFam9Zd1VZUS83eVEvODFqNTBzSVpka3BOM2VJRW9YR0ZOd0dSL0duUDNjTUxycmN6bGF4Qm1FDQpVOXErRmY4M0d2dnUyMEsxOEs4YU1MWmJ0dWFURFAvQmJwOHVjMzVFTVRKdjFqN1FpalBKWG9xU3l5cDM5dTN2DQpDdUZLMGRoZiswaW5za2NQdSs0THZUVWQxdEpYdjQ0cHdNREswY1lmamNXSGN2WUl3Qi90V1A0WUVZSEMyZDJDDQp6cTgwQzZNUjQrTlVGZUVnaXk3eFFON0IzSlF4cmlUNWZkSHhFZDl4L3FtK0ZZY3VWZXhKdGRwbUhtU3BremUxDQpsQzdBSDZRaS9xbERtRVBaaHBSMVVwRThkQXlqR3ZldXhYSG5jczI4dDZ3aHlMZU83RXQwb05zMWt3V1M0R0tODQpPYVRUOHNmcEFnTUJBQUVDZ2dFQUI1U25LNkdOekd2SWQxY1FEd0F5QjkyMUNXbE5yM1J1cVR3QUpGNXUyM0tEDQpiakk5YTNJTVM3cHBRbm10MkNnZXZZRFRCd2tQQ3dWUWVZczFJRGlKc2lUQ0xNMFBWRGVWRHNZWlV0eHBEUXVpDQorM20yQ0xOd2hTeGRLRmI0V1orTlZpZDNCUStHRm9DYlBJUXBPWHd0VnFpRTJlQmNBSWFsbUVEYWdPYnJkb1RzDQpPQ0k1bmJFWVIranBiUFNzZ2QrZzVNK1FIL2g4WGVXY0g0eHVFdUZlYncwTklTUC9wMUZaYnBhTTZGNjZuVkFRDQpLYm0rT2g3Zjg1dERwZ2xGQm01NlVGV3pQZXFOT3hJajlYQVpFcG5yNkozV3NQTW01eVVjcXEyV2F1QmhzNE9SDQo3UkZxM3h3bUlMRmxoMVVtdDNoOWJsdWJxZ3FZb0tTbE5RVE1vMlp1QVFLQmdRRGVQdWo4RDN4VEtHMEV4Z1ZODQpaQ1A2RFk3OE5LeTZSTWZOdWw3S00vcU5IREpZOXV3TUVrLzVBNFpJYW8xWHNCQlVMZWRGdFZBem1PQmFCTHgwDQovS3dqTWdob2ZMRVNHaGY3eGk1Yk9PMUl6Y29yTzdXbFFENkQ0ZmFJSDI1amFEMkFGc2x1OUhwNlRwa3Zqelk3DQp1c21SeVcxWEEwb3BORlpQRm5pWGFnU0dBUUtCZ1FEWmF1RHZiTDFRSlZnVjRnbUZiaXJ2a3BmamF4akpXZy8zDQo5cFRxRUdaYUltODZiQWdkZ2ZoZWJtZkNQOXRLd0RYUGpTc25PdTZjUnJXUDVmK0dlUTA0MDJaWE1NWnBEVkxrDQppaUh6TnljR2FMNE1iWGJNQ2ZHQ2VhSkZyM2RmNGNMSmp1R3NFYkNpYTZZVTYzK3lFMXZXcDZLaU10MytDTTEzDQpvei8yRUc3UjZRS0JnUUMwMHFhcGZzZit1T09LZ0xzTHJyQis0TTAzY253ZXladHZUWFdXT3hoZCsxVVRnVU9vDQp4clYrdTFsa1RoMVYvUkFzRFhVZ0NGZUt3NVcyYUNnVlh3ZUhVMHY0QjR2aVdJeXU4eDRBWnA3WkgyYWdLbUt1DQpZMGo1OEwydkh6T25lY2FnRXVvdGRvaTRQbjd3YlNzSkNmNjZ1UkpYTzN2NWJuWFN2MHU2bGkyOEFRS0JnUURJDQp4aElDQjRDclNsRVZwQzcyc00ybGZ0SVVpUW5TcHdDb0UyVmc0TlFqMkRpdTBxU0wyMEhvc2p2Ty9ma2NCbk9xDQp2c3BpNStFQkg2cjZ2NEpBUS9rWnlONXhGZkdqZ1ZKVENkeGdKVVk4Zk8xRHZMSS9xYzhFbGg1c0M2VkpQY29MDQpKNDd1djBkR05mS2d6dmlWRVp0MWxraHhVRmdBQjFEMmNpTFdzRVltUVFLQmdDWWdrNW1qSXZLeEc4RHNzWTFFDQpzTXZRWlZiWFRhdkplTm8zdUw4QVRtZk04NUNpb296YStGV0thTk10Y1lObGJGKzRPL2YxQVdBT0ZvQ0Zxb3FWDQpudDhNWXB3MS9hVlF0RXRGN2Q5dEM2MThING92WmlVbE95NUd2OFRRNEdxeWZmRWtEWEw2QkRUUmRHRnRjbzBSDQpoL0NqVytTK3N3NjNBeWcyZTVYL3g0U2kNCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0NCg==
kind: Secret
metadata:
  name: contoso.com
  namespace: test-infra
type: kubernetes.io/tls
