copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_1.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_2.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_3.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_4.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\FinishedAPPMainScreen.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\propertiespopup.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\BrowseByTagWithCallout.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\ASPNetPage.png"
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p2m_layouttags_mobile_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\Windows-Live-Writer_ASP_NET-MVC-4-Mobile-Features_D2FF_p2_layoutTagsDesktop_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\Windows-Live-Writer_ASP_NET-MVC-4-Mobile-Features_D2FF_p3_packageMgr_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\Windows-Live-Writer_ASP_NET-MVC-4-Mobile-Features_D2FF_p3_packageMgrConsole_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_afternuget_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_desktopviewwithmobilelink_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_desktopviewwithmobilelink_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\Windows-Live-Writer_ASP_NET-MVC-4-Mobile-Features_D2FF_p3_desktopBrowser_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_speakersdesktop_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_speakersconsistent_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_updatedspeakerview1_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_ps_data_filter_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_updatedspeakerview1_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_ps_data_filter_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_ps_data_filter_sc_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_tags_j_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_dates1_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_dates2_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_ps_data_filter_sc_thumb_1.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_scottha_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_ps_sessionsbyscottha_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_ps_data_filter_sc_thumb_2.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_scottha_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_ps_love_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\windows-live-writer_asp_net-mvc-4-mobile-features_d2ff_p3_love2_thumb.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_5.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_6.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_7.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_8.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_9.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_10.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_12.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_13.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_14.png
copy C:\Users\donglo\azure-content-pr\DevCenter\dotNET\Media\depoly_mobile_new_website_15.png