{
 "title": "Java metrics for Azure Container Apps",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "res",
    "label": "Resource",
    "query": {}
   },
   { "name": "podName", "label": "Replica" }
  ]
 },
 "panels": [
  { "title": "Conatiner App Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "UsageNanoCores",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Container Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "WorkingSetBytes",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Container Replica Number",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Container Replicas (pods)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "JvmMemoryUsed",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "P1D"
     },
     "subscription": "$sub"
    }
   ]
  },
  { "title": "JVM Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Heap memory used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "poolType", "filters": [ "HEAP" ], "operator": "eq" }
      ],
      "metricName": "JvmMemoryTotalUsed",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "PT5M"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Non-Heap memory used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "poolType", "filters": [ "NON_HEAP" ], "operator": "eq" }
      ],
      "metricName": "JvmMemoryTotalUsed",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "PT5M"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Heap memory limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "poolType", "filters": [ "HEAP" ], "operator": "eq" },
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "JvmMemoryTotalLimit",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Non-Heap memory limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "poolType", "filters": [ "NON_HEAP" ], "operator": "eq" },
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "JvmMemoryTotalLimit",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Heap memory comitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "poolType", "filters": [ "HEAP" ], "operator": "eq" },
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "JvmMemoryTotalCommitted",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Non-Heap memory comitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "poolType", "filters": [ "NON_HEAP" ], "operator": "eq" },
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "JvmMemoryTotalCommitted",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  { "title": "JVM Memory Usage Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Notice",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 50 },
   "options": {
    "content": "This blade gives you an memory usage analysis by JVM memory pool type.\nYou can paste a given replica name to the variable field above for analysis."
   },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Memory usage by pool",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 53 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "poolName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "podName", "filters": [ "$podName" ], "operator": "eq" }
      ],
      "metricName": "JvmMemoryUsed",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Memory limit by pool",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 63 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "poolName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "podName", "filters": [ "$podName" ], "operator": "eq" }
      ],
      "metricName": "JvmMemoryLimit",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Memory comitted by pool",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 73 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "poolName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "podName", "filters": [ "$podName" ], "operator": "eq" }
      ],
      "metricName": "JvmMemoryCommitted",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  { "title": "Memory Buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Buffer limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 84 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "poolName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "JvmBufferMemoryLimit",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Buffer usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 84 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "poolName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "JvmBufferMemoryUsage",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Buffer count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 93 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "poolName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "JvmBufferCount",
      "metricNamespace": "microsoft.app/containerapps",
      "resources": [
       { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "podName",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "gcName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "JvmGcCount",
        "metricNamespace": "microsoft.app/containerapps",
        "resources": [
         { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "GC duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 5 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "podName",
          "filters": [],
          "operator": "eq"
         },
         {
          "dimension": "gcName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "JvmGcDuration",
        "metricNamespace": "microsoft.app/containerapps",
        "resources": [
         { "metricNamespace": "microsoft.app/containerapps", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  }
 ]
}